.PHONY: run-api run-worker run-web stop-api stop-worker stop-web restart-api restart-worker

ROOT := ../..

run-api:
	$(MAKE) -C $(ROOT) run-api

run-worker:
	$(MAKE) -C $(ROOT) run-worker

run-web:
	$(MAKE) -C $(ROOT) run-web

stop-api:
	$(MAKE) -C $(ROOT) stop-api

stop-worker:
	$(MAKE) -C $(ROOT) stop-worker

stop-web:
	$(MAKE) -C $(ROOT) stop-web

restart-api:
	$(MAKE) -C $(ROOT) restart-api

restart-worker:
	$(MAKE) -C $(ROOT) restart-worker
