steps:
- name: gcr.io/cloud-builders/docker
  args: ["build","-t","gcr.io/$PROJECT_ID/recontent-api:$_TAG","."]
  dir: "."
- name: gcr.io/cloud-builders/docker
  args: ["push","gcr.io/$PROJECT_ID/recontent-api:$_TAG"]
- name: gcr.io/google.com/cloudsdktool/cloud-sdk
  args: [
    "gcloud","run","deploy","recontent-api",
    "--image","gcr.io/$PROJECT_ID/recontent-api:$_TAG",
    "--region","us-central1","--allow-unauthenticated",
    "--service-account","recontent-api-sa@recontent-472506.iam.gserviceaccount.com",
    "--set-env-vars","GOOGLE_CLOUD_PROJECT=$PROJECT_ID,GOOGLE_CLOUD_LOCATION=us-central1,GCS_BUCKET_RAW=recontent-raw,GCS_BUCKET_PROCESSED=recontent-processed,GCS_BUCKET_PUBLISHED=recontent-published,PUBSUB_TOPIC_JOBS=jobs,DB_INSTANCE_CONN_NAME=recontent-472506:us-central1:recontent-sql,DB_NAME=recontent,DB_USER=recontent,DB_PASSWORD=$(dbpass)",
    "--add-cloudsql-instances","recontent-472506:us-central1:recontent-sql"
  ]
availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/recontent-db-pass/versions/latest
    env: dbpass
substitutions:
  _TAG: "v1"
